### PR TITLE
Fixed nav link colors when selected and hover

### LINKED ISSUE #8: Fix this weird Active Page issue with the NavMenu
Not really sure what's causing this in terms of it being a styling vs. functional issue, but we needa resolve it at some point

https://github.com/dtran421/home-hub-v2/assets/26678529/78bf91b6-2723-4908-9efe-baae17b539b4

- [ ] The underlying component (I think it's a link or button, not sure) should not stay focused/active after being clicked (and the mouse button is released)
- [ ] Hovering over it should not turn the icon white (it should remain the active color)
- [ ] Clicking it should effectively do nothing (it shouldn't be disabled and should still be clickable, but it shouldn't refresh the page and/or re-navigate to the same page)

### PR DESCRIPTION
**Pull request by tot**
Fixes for https://github.com/dtran421/home-hub-v2/issues/8

- Keep active color for navbar icons
- Remove background on navbar icons after selected

### CODE REVIEW

File: src/components/NavMenu.tsx [hunk 1]
```diff
@@ -45,13 +45,17 @@ export const NavMenu = () => {
...
       <ul className="menu rounded-box menu-horizontal bg-base-200">
         {LINKS.map((link) => (
-          <li
-            key={link.href}
-            className={cn("", {
-              "text-accent": activePage === link.href.slice(1),
-            })}
-          >
-            <Link href={link.href}>{link.icon}</Link>
+          <li key={link.href} className={cn("bg-transparent")}>
```
Comment (dtran421) [inline src/components/NavMenu.tsx]: Why do we need `cn` here? We're not dealing with any conflicting classes. I think we should err on the side of not including `cn` if not necessary as it'll allow the IDE intellisense to work its magic on TW classes

File: src/components/NavMenu.tsx [hunk 2]
```diff
@@ -45,13 +45,17 @@ export const NavMenu = () => {
...
+            <div>
```
Comment (dtran421) [inline src/components/NavMenu.tsx]: Is this div seriously the fix?? Are we basically overriding the styles set by `daisyUI`? Do you know if there's a better way to do this, it feels a little crude

File: src/components/NavMenu.tsx [hunk 3]
```diff
@@ -45,13 +45,17 @@ export const NavMenu = () => {
...
+              <Link
+                href={link.href}
+                className={cn({
+                  "text-accent": activePage === link.href.slice(1),
```
Comment (dtran421) [inline src/components/NavMenu.tsx:53]: I wonder if we could move this out into the enclosing div? Would that break the styling again?

**Comment by dtran421** [comment]
Just a couple of comments, PTAL

**Review by dtran421 — CHANGES_REQUESTED** [review]
Just a couple of comments, PTAL

File: src/components/NavMenu.tsx (hunk 2 above)
Comment (tot) [reply src/components/NavMenu.tsx]: The fix is to wrap it in any sort of container because the CSS from `menu` parent class applies a background color and text color to the direct child of the `<li></li>` if it is an element with an onClick event (e.g. buttons and anchors).

If instead of a button or anchor link, it were a `<p></p>` element, the same behavior wouldn't be observed.

File: src/components/NavMenu.tsx (hunk 3 above)
Comment (tot) [reply src/components/NavMenu.tsx:53]: Yes

File: src/components/NavMenu.tsx (hunk 1 above)
Comment (tot) [reply src/components/NavMenu.tsx]: Fixed in latest commit

File: src/components/NavMenu.tsx [hunk 4]
```diff
@@ -45,19 +45,23 @@ export const NavMenu = () => {
...
+                {link.icon}
+              </Link>
+            </div>
           </li>
         ))}
       </ul>
       <div className="tooltip" data-tip="Logout">
         <button
-          className={cn("btn btn-square", "rounded-2xl")}
+          className="btn btn-square rounded-2xl"
```
Comment (dtran421) [inline src/components/NavMenu.tsx:64]: Why'd you make this change? I believe one of the `btn` classes set the border-radius, so we need `cn` to safely override the preexisting CSS class? Or am I misunderstanding how the underlying `twMerge` function works?

**Review by dtran421 — CHANGES_REQUESTED** [review]
A few more small things then I'll test later in the day, PTAL

File: src/components/NavMenu.tsx (hunk 2 above)
Comment (dtran421) [reply src/components/NavMenu.tsx]: In that case, can we use a `p` instead since it's more semantically accurate here?

File: src/components/NavMenu.tsx (hunk 4 above)
Comment (tot) [reply src/components/NavMenu.tsx:64]: There's no difference in this case between using cn and without it.

File: src/components/NavMenu.tsx (hunk 2 above)
Comment (tot) [reply src/components/NavMenu.tsx]: Changed it to a span.

File: src/components/NavMenu.tsx (hunk 4 above)
Comment (dtran421) [reply src/components/NavMenu.tsx:64]: I'm okay with making this change for now, but I worry that this might be a point of failure in the future if one of the `btn` classes conflicts with the `rounded-2xl` tw class.

**Comment by dtran421** [comment]
LGTM

**Review by dtran421 — APPROVED** [review]
LGTM
